version: "3"
services:
  server:
    container_name: server
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=dashboard_db
    restart: always

volumes:
  postgresdata: